# Generated by Django 3.2 on 2022-07-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favourite',
        ),
    ]
